name: lint
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  shellchecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: azohra/shell-linter@v0.6.0
      with:
        path: "src/**/*.sh"
        severity: "error" # [style, info, warning, error]